### ISSUE TITLE
Fatal erro ao ativar o plugin

### ISSUE THREAD

**Issue by brunoborges92** [asaferamos/woocommerce-correios-rastreio-parser#1]
Olá, estou querendo testar esse plugin porem da falta erro pois esta faltando o arquivo 'vendor/autoload.php', onde posso encontrar?

**Comment by asaferamos** [comment]
Olá. Tende rodar o `composer install` na pasta, pois ele depende de uma lib para funcionar

**Comment by brunoborges92** [comment]
Nossa, era só isso agora deu certo kkk sou meio noob.

**Comment by brunoborges92** [comment]
Em agora esta aparecendo esse erro. "ERRO AO BUSCAR CÓDIGO"

**Comment by asaferamos** [comment]
Vc seguiu as inscrições e instalou o plugin `woocommerce-correios` da minha [fork](https://github.com/asaferamos/woocommerce-correios/)?

**Comment by brunoborges92** [comment]
Instalei sim o pedido esta com o status "Order Dispatched"

**Comment by asaferamos** [comment]
Tinha um erro na versão da lib no _composer.json_. Criei um novo release. Pra funcionar corretamente agora, atualize o código e rode um `composer update`

**Comment by brunoborges92** [comment]
Funcionou, parabéns está muito bom, você vai disponibilizar no repositório do wordpress?

**Comment by asaferamos** [comment]
Pretendo melhorar algumas coisas depois, pra não depender muito de outros plugins, e lançar la sim.
